name: dev PR & Push

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Install go/wire
      run: go install github.com/google/wire/cmd/wire@latest

    - name: Set go/wire
      run: make di

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
